api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "xpoost-discount"
type = "function"
uid = "5bd5c634-8734-3491-927b-597bfeaa79686f278d17"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
